/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import Modelo.Cliente;
import Modelo.ListaCliente;
import Modelo.ListaProductos;
import Modelo.Producto;
import controladores.IniciarDatos;
import controladores.Validaciones;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mjavi
 */
public class frmFacturacion extends javax.swing.JFrame {

    /**
     * Creates new form frmFacturacion
     */
    public frmFacturacion() {
        initComponents();
        //cmbProductoCliente.setSelectedItem("Seleccione");
        //cmbProductoConsumidor.setSelectedItem("Seleccione");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescuentoCliente = new javax.swing.JTextField();
        btnVenderCliente = new javax.swing.JButton();
        cmbProductoCliente = new javax.swing.JComboBox<>();
        lblContadorCliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSubTotalCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIvaCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalCliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtNombreConsumidor = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtCedulaConsumidor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtPrecioConsumidor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDescuentoConsumidor = new javax.swing.JTextField();
        btnVenderConsumidor = new javax.swing.JButton();
        cmbProductoConsumidor = new javax.swing.JComboBox<>();
        lblContadorConsumidor = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtSubTotalConsumidor = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtIvaConsumidor = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtTotalConsumidor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnGuardarCliente = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardarProducto = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setText("Nombre completo:");

        txtCedulaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaClienteKeyTyped(evt);
            }
        });

        jLabel3.setText("Cédula:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCliente)
                    .addComponent(txtCedulaCliente)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));

        jLabel4.setText("Producto:");

        jLabel5.setText("Precio:");

        txtPrecioCliente.setEditable(false);
        txtPrecioCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setText("Descuento:");

        txtDescuentoCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnVenderCliente.setText("Vender Producto");
        btnVenderCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderClienteActionPerformed(evt);
            }
        });

        cmbProductoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoClienteActionPerformed(evt);
            }
        });

        lblContadorCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblContadorCliente.setText("Numero de productos vendidos: ");

        jLabel8.setText("Sub Total:");

        txtSubTotalCliente.setEditable(false);
        txtSubTotalCliente.setEnabled(false);

        jLabel9.setText("IVA:");

        jLabel10.setText("Total:");

        txtTotalCliente.setEditable(false);
        txtTotalCliente.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecioCliente)
                            .addComponent(jLabel6)
                            .addComponent(txtDescuentoCliente)
                            .addComponent(cmbProductoCliente, 0, 181, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(txtIvaCliente)
                            .addComponent(txtSubTotalCliente)
                            .addComponent(jLabel10)
                            .addComponent(txtTotalCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addComponent(btnVenderCliente)
                    .addComponent(lblContadorCliente))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProductoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIvaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVenderCliente)
                .addGap(18, 18, 18)
                .addComponent(lblContadorCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Datos del Cliente");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Datos del Producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Datos del Cliente");

        jPanel8.setBackground(new java.awt.Color(250, 250, 250));

        jLabel21.setText("Nombre completo:");

        txtNombreConsumidor.setEditable(false);
        txtNombreConsumidor.setText("Consumidor Final");
        txtNombreConsumidor.setEnabled(false);

        jLabel31.setText("Cédula:");

        txtCedulaConsumidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaConsumidorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedulaConsumidor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Datos del Producto");

        jPanel9.setBackground(new java.awt.Color(250, 250, 250));

        jLabel24.setText("Producto:");

        jLabel25.setText("Precio:");

        txtPrecioConsumidor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel26.setText("Descuento:");

        txtDescuentoConsumidor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnVenderConsumidor.setText("Vender Producto");
        btnVenderConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderConsumidorActionPerformed(evt);
            }
        });

        cmbProductoConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoConsumidorActionPerformed(evt);
            }
        });

        lblContadorConsumidor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblContadorConsumidor.setText("Numero de productos vendidos: ");

        jLabel28.setText("Sub Total:");

        txtSubTotalConsumidor.setEditable(false);
        txtSubTotalConsumidor.setEnabled(false);

        jLabel29.setText("IVA:");

        jLabel30.setText("Total:");

        txtTotalConsumidor.setEditable(false);
        txtTotalConsumidor.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(txtPrecioConsumidor)
                            .addComponent(jLabel26)
                            .addComponent(txtDescuentoConsumidor)
                            .addComponent(cmbProductoConsumidor, 0, 181, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(txtIvaConsumidor)
                            .addComponent(txtSubTotalConsumidor)
                            .addComponent(jLabel30)
                            .addComponent(txtTotalConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addComponent(btnVenderConsumidor)
                    .addComponent(lblContadorConsumidor))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProductoConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotalConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIvaConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuentoConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVenderConsumidor)
                .addGap(18, 18, 18)
                .addComponent(lblContadorConsumidor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Consumidor Final", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(250, 250, 250));

        jLabel11.setText("Nombres:");

        jLabel12.setText("Apellidos:");

        jLabel13.setText("Cédula:");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        btnGuardarCliente.setText("Guardar");
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(txtNombres)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos)
                    .addComponent(jLabel13)
                    .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarCliente)
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Nuevo Cliente");

        jPanel7.setBackground(new java.awt.Color(250, 250, 250));

        jLabel15.setText("Descripción del producto:");

        jLabel16.setText("Precio:");

        btnGuardarProducto.setText("Guardar");
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(txtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnGuardarProducto)
                .addGap(43, 43, 43))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Nuevo Producto");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Nuevo", jPanel5);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FACTURACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //DECLARACION DE VARIABLES GLOBALES
    ListaCliente listaCliente = new ListaCliente(); //Hacer referencia a la clase ListaCliente()
    ListaProductos listaProductos = new ListaProductos(); //Hacer referencia a la clase ListaProductos()
    //CONTADORES DE VENTAS
    int contadorCliente = 0;
    int contadorConsumidor = 0;

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        //VALIDAR QUE SE INGRESE SOLO NUMEROS AL PRESIONAR UNA TECLA
        if (txtCedula.getText().trim().length() < 10) {//validar la longitud de la cedula
            Validaciones.validarCedula(evt);//llamar a la clase validaciones para validar
        } else {
            evt.consume();//Si no es un numero el evento de typado se consume
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedulaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaClienteKeyTyped
        // TODO add your handling code here:
        //VALIDAR QUE SE INGRESE SOLO NUMEROS AL PRESIONAR UNA TECLA
        if (txtCedulaCliente.getText().trim().length() < 10) { //validar la longitud de la cedula
            Validaciones.validarCedula(evt);//llamar a la clase validaciones para validar
        } else {
            evt.consume();//Si no es un numero el evento de typado se consume
        }
    }//GEN-LAST:event_txtCedulaClienteKeyTyped

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        // TODO add your handling code here:
        //VALIDAR QUE NO INGRESE CAMPOS VACIOS
        if (txtNombres.getText().trim().length() > 0 && txtApellidos.getText().trim().length() > 0 && txtCedula.getText().trim().length() > 0) {
            if (txtCedula.getText().trim().length() > 0 && txtCedula.getText().trim().length() <= 10) {
                //LLAMAR A LA CLSE ListaCliente para guardar un nuevo elemento
                listaCliente.acolar(txtNombres.getText(), txtApellidos.getText(), txtCedula.getText());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error de validación, la cédula debe tener 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pueden ingresar valores nulos.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        // TODO add your handling code here:
        //VALIDAR QUE NO SE GUARDEN CAMPOS VACIOS
        if (!(txtProducto.getText().trim().length() == 0) && !(txtPrecio.getText().trim().length() == 0)) {
            listaProductos.acolar(txtProducto.getText(), Double.parseDouble(txtPrecio.getText()));
            //Llamar a la clase IniciarDatos y llenar el combobox con los productos ingresados
            IniciarDatos.cargarComboProductos(cmbProductoCliente, listaProductos.getProducto());
            //copiar el modelo del combo de los productos al de los consumidores
            cmbProductoConsumidor.setModel(cmbProductoCliente.getModel());
//            cmbProductoCliente.removeItemAt(0);
//            cmbProductoConsumidor.removeItemAt(0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pueden ingresar valores nulos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void cmbProductoConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoConsumidorActionPerformed
        // TODO add your handling code here:
        Producto aux = listaProductos.getProducto(); // copiar la lista de los productos
        String precio1 = "";
        String descuento = "0.0";
        while (aux != null) { //recorrer la lista de los productos
            if (aux.getDescripcion() == cmbProductoConsumidor.getSelectedItem().toString()) { //preguntar si el item seleccionado coincide con alguno de la lista
                //obtener el precio del item seleccionado
                precio1 = String.valueOf(aux.getPrecio());
                //preguntar por licuadora y cocina para una descuento del 5%
                if (aux.getDescripcion().toString().equals("licuadora") || aux.getDescripcion().toString().equals("cocina")) {
                    descuento = "0.5";
                }
            }
            aux = aux.getSiguienteProducto();
        }
        txtPrecioConsumidor.setText(precio1);
        txtDescuentoConsumidor.setText(descuento);
    }//GEN-LAST:event_cmbProductoConsumidorActionPerformed

    private void cmbProductoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoClienteActionPerformed
        // TODO add your handling code here:
        Producto aux = listaProductos.getProducto();// copiar la lista de los clientes
        String precio1 = "";
        String descuento = "0.0";
        while (aux != null) { //recorrer la lista de los clientes
            if (aux.getDescripcion() == cmbProductoCliente.getSelectedItem().toString()) { //preguntar si el item seleccionado coincide con alguno de la lista
                //obtener el precio del item seleccionado
                precio1 = String.valueOf(aux.getPrecio());
                //preguntar por licuadora y cocina para una descuento del 5%
                if (aux.getDescripcion().toString().equals("licuadora") || aux.getDescripcion().toString().equals("cocina")) {
                    descuento = "0.5";
                }
            }
            aux = aux.getSiguienteProducto();
        }
        txtPrecioCliente.setText(precio1);
        System.out.println("El des es: " + descuento);
        txtDescuentoCliente.setText(descuento);
    }//GEN-LAST:event_cmbProductoClienteActionPerformed


    private void txtCedulaConsumidorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaConsumidorKeyTyped
        // TODO add your handling code here:
        //VALIDACIONES PARA QUE SE INGRESE SOLO NUMEROS
        if (txtCedulaConsumidor.getText().trim().length() < 10) { //VALIDAR QUE SOLO SE INGRESE 10 DIGITOS
            Validaciones.validarCedula(evt);// llamar a la clase validaciones para validar
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaConsumidorKeyTyped


    private void btnVenderClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderClienteActionPerformed
        // TODO add your handling code here:
        String item = cmbProductoCliente.getSelectedItem().toString();
        //VALIDACIONES PARA VALORES NULOS
        if (txtNombreCliente.getText().trim().length() > 0
                && txtPrecioCliente.getText().trim().length() > 0
                && txtIvaCliente.getText().trim().length() > 0) {
            //VALIDAR LA LONGITUD DE LA CEDULA
            if (txtCedulaCliente.getText().trim().length() == 10) {
                double precio = Double.parseDouble(txtPrecioCliente.getText());
                double descuento = 0.0;
                if (item.equals("licuadora") || item.equals("cocina")) {
                    descuento = Double.parseDouble(txtDescuentoCliente.getText());
                } else {
                    descuento = 1;
                }
                //PROCEDIMIENTO PARA REALIZAR LOS CALCULOS
                double subTotal = precio * descuento;
                double iva = Double.parseDouble(txtIvaCliente.getText());
                double subIva = subTotal * iva;
                double total = subTotal + subIva;
                txtSubTotalCliente.setText(String.valueOf(subTotal));
                txtTotalCliente.setText(String.valueOf(total));

                //MOSTRAR MENSAJE DE LOS DETALLES DE LA VENTA
                JOptionPane.showMessageDialog(rootPane, "DETALLE DE LA VENTA\n"
                        + "Nombre del producto: " + cmbProductoCliente.getSelectedItem().toString() + "\n"
                        + "Precio: " + txtPrecioCliente.getText() + "\n"
                        + "Descuento: " + txtDescuentoCliente.getText() + "\n"
                        + "SubTotal: " + txtSubTotalCliente.getText() + "\n"
                        + "IVA: " + txtIvaCliente.getText() + "\n"
                        + "Precio Final: " + txtTotalCliente.getText() + "\n",
                        "DETALLE DE LA VENTA", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error de validación, la cédula debe tener 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pueden ingresar valores nulos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        contadorCliente++;
        lblContadorCliente.setText("Número de productos vendidos: " + contadorCliente);

    }//GEN-LAST:event_btnVenderClienteActionPerformed

    private void btnVenderConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderConsumidorActionPerformed
        // TODO add your handling code here:
        String item = cmbProductoConsumidor.getSelectedItem().toString();
        //VALIDACIONES PARA VALORES NULOS
        if (txtPrecioConsumidor.getText().trim().length() > 0
                && txtIvaConsumidor.getText().trim().length() > 0) {
            //VALIDACIONES PARA LA LONGIUTD DE LA CEDULA
            if (txtCedulaConsumidor.getText().trim().length() == 10) {
                double precio = Double.parseDouble(txtPrecioConsumidor.getText());
                double descuento = 0.0;
                if (item.equals("licuadora") || item.equals("cocina")) {
                    descuento = Double.parseDouble(txtDescuentoConsumidor.getText());
                } else {
                    descuento = 1;
                }
                //PROCEDIMIENTO PARA REALIZAR LOS CALCULOS
                double subTotal = precio * descuento;
                double iva = Double.parseDouble(txtIvaConsumidor.getText());
                double subIva = subTotal * iva;
                double total = subTotal + subIva;
                txtSubTotalConsumidor.setText(String.valueOf(subTotal));
                txtTotalConsumidor.setText(String.valueOf(total));

                //MOSTRAR MENSAJES DE LOS DETALLES DE LA VENTA
                JOptionPane.showMessageDialog(rootPane, "DETALLE DE LA VENTA\n"
                        + "Nombre del producto: " + cmbProductoConsumidor.getSelectedItem().toString() + "\n"
                        + "Precio: " + txtPrecioConsumidor.getText() + "\n"
                        + "Descuento: " + txtDescuentoConsumidor.getText() + "\n"
                        + "SubTotal: " + txtSubTotalConsumidor.getText() + "\n"
                        + "IVA: " + txtIvaConsumidor.getText() + "\n"
                        + "Precio Final: " + txtTotalConsumidor.getText() + "\n",
                        "DETALLE DE LA VENTA", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error de validación, la cédula debe tener 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pueden ingresar valores nulos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        contadorConsumidor++;
        lblContadorConsumidor.setText("Número de productos vendidos: " + contadorConsumidor);

    }//GEN-LAST:event_btnVenderConsumidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnVenderCliente;
    private javax.swing.JButton btnVenderConsumidor;
    private javax.swing.JComboBox<String> cmbProductoCliente;
    private javax.swing.JComboBox<String> cmbProductoConsumidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblContadorCliente;
    private javax.swing.JLabel lblContadorConsumidor;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaConsumidor;
    private javax.swing.JTextField txtDescuentoCliente;
    private javax.swing.JTextField txtDescuentoConsumidor;
    private javax.swing.JTextField txtIvaCliente;
    private javax.swing.JTextField txtIvaConsumidor;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreConsumidor;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioCliente;
    private javax.swing.JTextField txtPrecioConsumidor;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSubTotalCliente;
    private javax.swing.JTextField txtSubTotalConsumidor;
    private javax.swing.JTextField txtTotalCliente;
    private javax.swing.JTextField txtTotalConsumidor;
    // End of variables declaration//GEN-END:variables
}
